### ISSUE TITLE
I can not log in using edited items

### ISSUE THREAD

**Issue by nanika0000** [k0np4ku/Azur-Lane-LuaHelper#5]
[OK.txt](https://github.com/k0np4ku/Azur-Lane-LuaHelper/files/2238605/OK.txt)
[NG.txt](https://github.com/k0np4ku/Azur-Lane-LuaHelper/files/2238606/NG.txt)
Trying to use something with added hands will not proceed from loading

**Comment by k0np4ku** [comment]
Encrypt the lua before repacking

**Comment by nanika0000** [comment]
It was solved by following advice.
I apologize to you for a fuss over
